export const banks = [
  {
    id: "ncre3",
    name: "计算机三级",
    shortName: "三级",
    target: "全国计算机等级考试三级",
    passLine: 60,
    modules: ["网络技术", "数据库技术", "信息安全技术", "嵌入式系统开发技术", "Linux应用与开发技术"],
  },
  {
    id: "engineer",
    name: "软考",
    shortName: "软考",
    target: "中国计算机技术与软件专业技术资格（水平）考试",
    passLine: 45,
    modules: ["公共基础", "程序员", "软件设计师", "网络工程师", "数据库系统工程师", "软件评测师", "系统架构设计师", "信息系统项目管理师"],
  },
];

const ncreSource = "NCRE 2025 版三级考试大纲考点改编";
const engineerSource = "中国计算机技术与软件专业技术资格（水平）考试官方考试设置与近年高频考点改编";

export const examProfiles = [
  {
    bankId: "engineer",
    level: "初级",
    qualification: "程序员",
    subjects: ["基础知识", "应用技术"],
    passRule: "各科满分 75 分，通常各科均需达到 45 分及以上。",
  },
  {
    bankId: "engineer",
    level: "中级",
    qualification: "软件设计师",
    subjects: ["基础知识", "应用技术"],
    passRule: "各科满分 75 分，通常各科均需达到 45 分及以上。",
  },
  {
    bankId: "engineer",
    level: "中级",
    qualification: "网络工程师",
    subjects: ["基础知识", "应用技术"],
    passRule: "各科满分 75 分，通常各科均需达到 45 分及以上。",
  },
  {
    bankId: "engineer",
    level: "中级",
    qualification: "数据库系统工程师",
    subjects: ["基础知识", "应用技术"],
    passRule: "各科满分 75 分，通常各科均需达到 45 分及以上。",
  },
  {
    bankId: "engineer",
    level: "中级",
    qualification: "软件评测师",
    subjects: ["基础知识", "应用技术"],
    passRule: "各科满分 75 分，通常各科均需达到 45 分及以上。",
  },
  {
    bankId: "engineer",
    level: "高级",
    qualification: "系统架构设计师",
    subjects: ["综合知识", "案例分析", "论文"],
    passRule: "各科满分 75 分，通常各科均需达到 45 分及以上。",
  },
  {
    bankId: "engineer",
    level: "高级",
    qualification: "信息系统项目管理师",
    subjects: ["综合知识", "案例分析", "论文"],
    passRule: "各科满分 75 分，通常各科均需达到 45 分及以上。",
  },
];

export const sourceNotes = [
  {
    name: "全国计算机等级考试三级网络技术考试大纲（2025年版）",
    url: "https://ncre.neea.edu.cn/res/Home/2412/03a23dc61db2859d591b94fcabbacdcf.pdf",
  },
  {
    name: "全国计算机等级考试三级数据库技术考试大纲（2025年版）",
    url: "https://m.jsjdjks.com/nd.jsp?id=70",
  },
  {
    name: "全国计算机等级考试三级信息安全技术考试大纲（2025年版）",
    url: "https://www.jsjdjks.com/sys-nd/72.html",
  },
  {
    name: "软考软件设计师考试大纲（2018年审定通过）",
    url: "https://www.miiteec.org.cn/news_details?code=258",
  },
  {
    name: "51CTO 软考章节练习目录参考",
    url: "https://rk.51cto.com/t/n/chapter-manage/list/",
  },
];

export const questions = [
  {
    id: "n3-net-001",
    bankId: "ncre3",
    module: "网络技术",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2025,
    stem: "在中小型网络规划中，进行 IP 地址规划时最先需要明确的是哪一项？",
    options: ["交换机品牌", "业务部门和主机规模", "机柜颜色", "网线护套材料"],
    answer: 1,
    explanation: "IP 地址规划要先根据组织结构、业务区域、主机数量和未来扩展预留来划分网段，再选择掩码、网关和路由策略。",
    points: ["IP地址规划", "子网划分", "网络需求分析"],
  },
  {
    id: "n3-net-002",
    bankId: "ncre3",
    module: "网络技术",
    type: "单选",
    difficulty: "基础",
    sourceType: "模拟题",
    year: 2026,
    stem: "TCP/IP 体系中负责端到端可靠传输、确认与重传的是哪一层？",
    options: ["网络接口层", "网际层", "传输层", "应用层"],
    answer: 2,
    explanation: "TCP 位于传输层，提供面向连接、确认、重传、流量控制和拥塞控制；IP 位于网际层，主要负责寻址与路由。",
    points: ["TCP", "传输层", "可靠传输"],
  },
  {
    id: "n3-net-003",
    bankId: "ncre3",
    module: "网络技术",
    type: "多选",
    difficulty: "提高",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "下列哪些内容通常属于网络综合布线方案需要考虑的因素？",
    options: ["工作区信息点数量", "水平子系统线缆长度", "配线间位置", "数据库事务隔离级别"],
    answer: [0, 1, 2],
    explanation: "综合布线关注工作区、水平子系统、垂直干线、设备间、管理间等物理布线要素；事务隔离级别属于数据库内容。",
    points: ["综合布线", "水平子系统", "设备间"],
  },
  {
    id: "n3-net-004",
    bankId: "ncre3",
    module: "网络技术",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "某公司要隔离财务部与研发部广播域，最常用的二层网络技术是？",
    options: ["NAT", "VLAN", "DNS", "ARP"],
    answer: 1,
    explanation: "VLAN 可以在交换网络中划分逻辑广播域，常用于部门隔离、权限控制和网络管理。",
    points: ["VLAN", "广播域", "二层交换"],
  },
  {
    id: "n3-route-001",
    bankId: "ncre3",
    module: "网络技术",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2023,
    stem: "交换机启用 STP 的主要目的是？",
    options: ["提高 HTTP 下载速度", "防止二层环路", "加密交换机配置", "替代 IP 路由"],
    answer: 1,
    explanation: "STP 通过阻塞冗余链路中的部分端口，避免广播风暴和 MAC 地址表震荡，是交换网络冗余设计中的基础机制。",
    points: ["STP", "二层环路", "广播风暴"],
  },
  {
    id: "n3-route-002",
    bankId: "ncre3",
    module: "网络技术",
    type: "多选",
    difficulty: "综合",
    sourceType: "模拟题",
    year: 2026,
    stem: "配置静态路由时通常需要指定哪些信息？",
    options: ["目的网络", "子网掩码或前缀长度", "下一跳地址或出接口", "用户登录密码明文"],
    answer: [0, 1, 2],
    explanation: "静态路由的核心要素是目的网络、掩码和转发方向。登录密码不是路由条目的组成部分。",
    points: ["静态路由", "下一跳", "路由表"],
  },
  {
    id: "n3-route-003",
    bankId: "ncre3",
    module: "网络技术",
    type: "单选",
    difficulty: "提高",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "NAT 技术在企业出口路由器上最常见的作用是？",
    options: ["把私有地址转换为公网地址访问互联网", "把域名解析为 IP 地址", "检测磁盘坏道", "替换交换机生成树协议"],
    answer: 0,
    explanation: "NAT 常用于企业内网私有地址到公网地址的转换，缓解公网地址不足，并隐藏内部地址结构。",
    points: ["NAT", "私有地址", "出口路由"],
  },
  {
    id: "n3-db-001",
    bankId: "ncre3",
    module: "数据库技术",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "关系数据库中，能够唯一标识关系中元组且不含多余属性的属性组称为？",
    options: ["外键", "候选码", "视图", "触发器"],
    answer: 1,
    explanation: "候选码能唯一标识元组且具有最小性；从候选码中选定一个作为主要标识时称为主键。",
    points: ["候选码", "主键", "关系模型"],
  },
  {
    id: "n3-db-002",
    bankId: "ncre3",
    module: "数据库技术",
    type: "单选",
    difficulty: "提高",
    sourceType: "真题考点改编",
    year: 2025,
    stem: "SQL 查询中，若要按部门统计员工平均工资，最可能使用的子句组合是？",
    options: ["GROUP BY 与 AVG", "ORDER BY 与 DELETE", "CREATE 与 DROP", "GRANT 与 REVOKE"],
    answer: 0,
    explanation: "分组统计要用 GROUP BY 指定分组字段，并用 AVG、SUM、COUNT 等聚合函数计算统计值。",
    points: ["GROUP BY", "聚合函数", "SQL查询"],
  },
  {
    id: "n3-db-003",
    bankId: "ncre3",
    module: "数据库技术",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "事务的 ACID 特性中，要求事务中的操作要么全部完成、要么全部撤销的是？",
    options: ["原子性", "一致性", "隔离性", "持久性"],
    answer: 0,
    explanation: "原子性强调事务不可分割；一致性强调事务前后满足完整性约束；隔离性处理并发影响；持久性保证提交后结果不丢失。",
    points: ["事务", "ACID", "回滚"],
  },
  {
    id: "n3-db-004",
    bankId: "ncre3",
    module: "数据库技术",
    type: "多选",
    difficulty: "综合",
    sourceType: "真题考点改编",
    year: 2025,
    stem: "下列哪些属于数据库运行维护或性能优化中常见的工作？",
    options: ["建立合适索引", "备份与恢复策略", "权限管理", "修改显示器刷新率"],
    answer: [0, 1, 2],
    explanation: "数据库维护关注索引、备份恢复、安全权限、空间管理、故障处理等；显示器刷新率与数据库运行维护无关。",
    points: ["索引", "备份恢复", "安全管理"],
  },
  {
    id: "n3-sec-001",
    bankId: "ncre3",
    module: "信息安全技术",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2023,
    stem: "数字签名主要用于保证消息的完整性、身份鉴别以及哪一项安全属性？",
    options: ["机密性", "不可否认性", "可用性", "压缩率"],
    answer: 1,
    explanation: "数字签名使用私钥签名、公钥验证，能证明签名者身份并防止事后否认；机密性通常依赖加密。",
    points: ["数字签名", "公钥密码", "不可否认性"],
  },
  {
    id: "n3-sec-002",
    bankId: "ncre3",
    module: "信息安全技术",
    type: "多选",
    difficulty: "提高",
    sourceType: "真题考点改编",
    year: 2025,
    stem: "等级保护和风险评估工作中通常需要关注哪些内容？",
    options: ["资产识别", "威胁与脆弱性分析", "安全控制措施", "网页字体大小"],
    answer: [0, 1, 2],
    explanation: "风险评估通常围绕资产、威胁、脆弱性、已有控制和风险处置展开；网页字体大小不是核心安全风险项。",
    points: ["风险评估", "等级保护", "安全控制"],
  },
  {
    id: "n3-sec-003",
    bankId: "ncre3",
    module: "信息安全技术",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "对称加密与非对称加密相比，最典型的特点是？",
    options: ["加密和解密使用同一密钥", "不需要任何密钥", "只能用于数字签名", "只能保护可用性"],
    answer: 0,
    explanation: "对称加密使用同一密钥进行加密和解密，效率高但密钥分发困难；非对称加密使用公钥和私钥。",
    points: ["对称加密", "非对称加密", "密钥管理"],
  },
  {
    id: "n3-web-001",
    bankId: "ncre3",
    module: "信息安全技术",
    type: "多选",
    difficulty: "综合",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "下列哪些措施有助于降低 SQL 注入风险？",
    options: ["参数化查询", "输入白名单校验", "数据库最小权限", "拼接用户输入生成 SQL"],
    answer: [0, 1, 2],
    explanation: "参数化查询能分离指令与数据，白名单校验减少非法输入，最小权限降低攻击影响；直接拼接 SQL 是高风险做法。",
    points: ["SQL注入", "参数化查询", "最小权限"],
  },
  {
    id: "n3-web-002",
    bankId: "ncre3",
    module: "信息安全技术",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "为了防止存储型 XSS，服务端在输出用户提交内容到页面时最关键的处理是？",
    options: ["HTML 转义或上下文相关编码", "删除所有日志", "关闭数据库索引", "改用 UDP 传输"],
    answer: 0,
    explanation: "XSS 防护要根据输出上下文进行 HTML、属性、JavaScript 等编码，并结合输入校验、CSP、HttpOnly Cookie 等措施。",
    points: ["XSS", "输出编码", "CSP"],
  },
  {
    id: "n3-test-001",
    bankId: "ncre3",
    module: "嵌入式系统开发技术",
    type: "单选",
    difficulty: "基础",
    sourceType: "模拟题",
    year: 2026,
    stem: "嵌入式系统中，实时操作系统最关注的核心特性通常是？",
    options: ["任务响应的确定性", "网页动画效果", "数据库报表样式", "办公软件兼容性"],
    answer: 0,
    explanation: "嵌入式实时系统强调在规定时间内完成响应，调度、优先级、中断处理和资源受限设计都是高频考点。",
    points: ["嵌入式系统", "实时操作系统", "任务调度"],
  },
  {
    id: "n3-test-002",
    bankId: "ncre3",
    module: "Linux应用与开发技术",
    type: "单选",
    difficulty: "提高",
    sourceType: "真题考点改编",
    year: 2023,
    stem: "Linux 中，若要查看当前目录下文件和子目录的详细权限信息，常用命令是？",
    options: ["ls -l", "cd ..", "pwd -p", "kill -9"],
    answer: 0,
    explanation: "`ls -l` 会显示权限、属主、属组、大小、时间等详细信息；Linux 应用与开发题常考文件权限、进程、Shell 和基础开发工具。",
    points: ["Linux命令", "文件权限", "Shell"],
  },
  {
    id: "se-eng-001",
    bankId: "engineer",
    module: "软件设计师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "软件生命周期中，明确系统必须完成哪些功能和约束的阶段是？",
    options: ["需求分析", "概要设计", "编码", "部署"],
    answer: 0,
    explanation: "需求分析解决“做什么”，产出需求规格说明；设计阶段解决“怎么做”。",
    points: ["需求分析", "SRS", "生命周期"],
  },
  {
    id: "se-eng-002",
    bankId: "engineer",
    module: "软件设计师",
    type: "多选",
    difficulty: "提高",
    sourceType: "真题考点改编",
    year: 2023,
    stem: "下列哪些属于常见的软件过程模型？",
    options: ["瀑布模型", "螺旋模型", "增量模型", "哈希模型"],
    answer: [0, 1, 2],
    explanation: "瀑布、螺旋、增量、迭代和敏捷都是常见过程模型；哈希是摘要算法相关概念。",
    points: ["过程模型", "瀑布", "螺旋"],
  },
  {
    id: "se-eng-003",
    bankId: "engineer",
    module: "软件设计师",
    type: "单选",
    difficulty: "综合",
    sourceType: "模拟题",
    year: 2026,
    stem: "面向对象设计中，类的内部实现细节对外隐藏，外部通过接口访问，体现的是？",
    options: ["封装", "继承", "多态", "冒泡"],
    answer: 0,
    explanation: "封装把数据和操作组织在对象内部，并隐藏实现细节；继承强调复用与扩展，多态强调同一接口不同实现。",
    points: ["面向对象", "封装", "类设计"],
  },
  {
    id: "se-ds-001",
    bankId: "engineer",
    module: "软件设计师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2025,
    stem: "二分查找适用的基本前提是待查找序列？",
    options: ["按关键字有序", "全部为负数", "只能存储在链表中", "长度必须为偶数"],
    answer: 0,
    explanation: "二分查找每次与中间元素比较并缩小查找范围，要求顺序表按关键字有序。",
    points: ["二分查找", "有序表", "时间复杂度"],
  },
  {
    id: "se-ds-002",
    bankId: "engineer",
    module: "软件设计师",
    type: "单选",
    difficulty: "基础",
    sourceType: "模拟题",
    year: 2026,
    stem: "具有先进先出特性的数据结构是？",
    options: ["栈", "队列", "堆", "二叉树"],
    answer: 1,
    explanation: "队列遵循 FIFO，队尾入队、队头出队；栈遵循 LIFO，后进先出。",
    points: ["队列", "FIFO", "栈"],
  },
  {
    id: "se-ds-003",
    bankId: "engineer",
    module: "软件设计师",
    type: "单选",
    difficulty: "提高",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "若一棵二叉树的中序遍历结果是有序序列，该树最可能满足哪种性质？",
    options: ["二叉排序树", "完全二叉树", "哈夫曼树", "线索二叉树"],
    answer: 0,
    explanation: "二叉排序树左子树关键字小于根、右子树关键字大于根，其中序遍历可得到有序序列。",
    points: ["二叉排序树", "中序遍历", "查找树"],
  },
  {
    id: "se-os-001",
    bankId: "engineer",
    module: "软件设计师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "进程从就绪态变为运行态通常是因为？",
    options: ["被 CPU 调度选中", "等待 I/O 完成", "主动申请磁盘空间", "被装入外存"],
    answer: 0,
    explanation: "就绪态进程已具备运行条件，等待处理机；被调度程序选中后进入运行态。",
    points: ["进程状态", "调度", "就绪态"],
  },
  {
    id: "se-os-002",
    bankId: "engineer",
    module: "软件设计师",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "分页存储管理中，逻辑地址通常由页号和什么组成？",
    options: ["页内位移", "进程名", "文件扩展名", "网关地址"],
    answer: 0,
    explanation: "分页系统把逻辑地址分为页号和页内位移，通过页表把页号映射到物理块号。",
    points: ["分页管理", "页表", "地址转换"],
  },
  {
    id: "se-db-001",
    bankId: "engineer",
    module: "数据库系统工程师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2023,
    stem: "关系模式 R 中，若非主属性完全依赖于候选码且不存在部分函数依赖，通常至少达到？",
    options: ["第一范式", "第二范式", "BCNF", "非规范化"],
    answer: 1,
    explanation: "第二范式要求在第一范式基础上消除非主属性对候选码的部分函数依赖。",
    points: ["范式", "函数依赖", "2NF"],
  },
  {
    id: "se-db-002",
    bankId: "engineer",
    module: "数据库系统工程师",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "在数据库并发控制中，两段锁协议主要用于保证调度的？",
    options: ["可串行化", "可压缩性", "图像清晰度", "网络吞吐量"],
    answer: 0,
    explanation: "两段锁协议要求事务先获得锁、后释放锁，释放后不能再申请新锁，可用于保证冲突可串行化。",
    points: ["并发控制", "两段锁", "可串行化"],
  },
  {
    id: "se-comp-001",
    bankId: "engineer",
    module: "公共基础",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2025,
    stem: "CPU 中负责算术运算和逻辑运算的部件是？",
    options: ["ALU", "Cache", "I/O 接口", "外存"],
    answer: 0,
    explanation: "ALU 是算术逻辑单元，完成加减、逻辑与或非、比较等运算；控制器负责指令控制。",
    points: ["ALU", "CPU", "运算器"],
  },
  {
    id: "se-comp-002",
    bankId: "engineer",
    module: "公共基础",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "Cache 的主要作用是？",
    options: ["缓解 CPU 与主存速度不匹配", "永久保存操作系统", "替代所有外设", "加密源代码"],
    answer: 0,
    explanation: "Cache 利用程序局部性，在 CPU 和主存之间保存近期常用数据或指令，以提高平均访问速度。",
    points: ["Cache", "局部性", "存储层次"],
  },
  {
    id: "se-arch-001",
    bankId: "engineer",
    module: "系统架构设计师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "MVC 中负责业务数据和业务规则的部分是？",
    options: ["Model", "View", "Controller", "Router"],
    answer: 0,
    explanation: "Model 负责业务数据和业务逻辑；View 负责展示；Controller 处理输入并协调模型和视图。",
    points: ["MVC", "模型", "职责分离"],
  },
  {
    id: "se-arch-002",
    bankId: "engineer",
    module: "系统架构设计师",
    type: "多选",
    difficulty: "综合",
    sourceType: "模拟题",
    year: 2026,
    stem: "微服务架构通常需要重点治理哪些问题？",
    options: ["服务发现", "接口契约", "分布式事务", "单机内存寻址"],
    answer: [0, 1, 2],
    explanation: "微服务拆分后会带来服务发现、接口兼容、链路追踪、限流熔断和分布式事务等治理问题。",
    points: ["微服务", "服务治理", "分布式事务"],
  },
  {
    id: "se-pm-001",
    bankId: "engineer",
    module: "信息系统项目管理师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2023,
    stem: "PERT 图中，决定项目最短完成时间的一系列活动构成？",
    options: ["关键路径", "风险清单", "需求基线", "测试报告"],
    answer: 0,
    explanation: "关键路径是从开始到结束持续时间最长的路径，决定项目最短工期；关键活动延误会影响总工期。",
    points: ["PERT", "关键路径", "进度管理"],
  },
  {
    id: "se-pm-002",
    bankId: "engineer",
    module: "信息系统项目管理师",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "配置管理中，基线的主要作用是？",
    options: ["作为受控变更的稳定参照", "替代单元测试", "自动编写需求", "删除版本历史"],
    answer: 0,
    explanation: "基线是经过评审确认的配置项集合，后续变更需要受控处理，便于追踪、审计和回退。",
    points: ["配置管理", "基线", "变更控制"],
  },
  {
    id: "se-law-001",
    bankId: "engineer",
    module: "公共基础",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "软件著作权通常保护的是软件的哪一类表达？",
    options: ["源程序和文档等表达形式", "算法思想本身", "数学公式本身", "开发者的办公桌"],
    answer: 0,
    explanation: "著作权保护作品的表达形式，如程序代码和文档；思想、方法、算法本身通常不由著作权直接保护。",
    points: ["软件著作权", "表达保护", "知识产权"],
  },
  {
    id: "se-law-002",
    bankId: "engineer",
    module: "公共基础",
    type: "单选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "在软件质量标准中，可靠性主要关注软件在规定条件下和规定时间内？",
    options: ["完成规定功能的能力", "界面颜色数量", "源代码行数", "安装包体积"],
    answer: 0,
    explanation: "可靠性关注软件在规定条件、规定时间内维持规定功能的能力，常涉及成熟性、容错性和可恢复性。",
    points: ["软件质量", "可靠性", "质量属性"],
  },
  {
    id: "rk-prog-001",
    bankId: "engineer",
    module: "程序员",
    type: "单选",
    difficulty: "基础",
    sourceType: "软考高频考点改编",
    year: 2025,
    stem: "程序员考试中，若要求判断一个算法随输入规模 n 增长时运行时间的增长趋势，通常分析的是？",
    options: ["时间复杂度", "界面分辨率", "数据库用户名", "项目合同金额"],
    answer: 0,
    explanation: "算法复杂度用于描述算法资源消耗随输入规模变化的趋势，程序员考试常结合循环、递归和基本数据结构考查。",
    points: ["程序员", "算法基础", "时间复杂度"],
  },
  {
    id: "rk-prog-002",
    bankId: "engineer",
    module: "程序员",
    type: "单选",
    difficulty: "基础",
    sourceType: "模拟题",
    year: 2026,
    stem: "C 语言中，数组名在多数表达式中通常可转换为指向数组首元素的？",
    options: ["指针", "文件", "线程", "数据库"],
    answer: 0,
    explanation: "程序员级别常考基础语法、指针、数组、函数和简单算法。数组名在表达式中常退化为首元素地址。",
    points: ["C语言", "数组", "指针"],
  },
  {
    id: "rk-net-001",
    bankId: "engineer",
    module: "网络工程师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "网络工程师考试中，OSPF 协议属于哪一类路由协议？",
    options: ["链路状态型 IGP", "距离矢量型 EGP", "应用层文件传输协议", "二层环路检测协议"],
    answer: 0,
    explanation: "OSPF 是链路状态型内部网关协议，使用 LSDB 和 SPF 算法计算最短路径。",
    points: ["网络工程师", "OSPF", "路由协议"],
  },
  {
    id: "rk-net-002",
    bankId: "engineer",
    module: "网络工程师",
    type: "多选",
    difficulty: "提高",
    sourceType: "模拟题",
    year: 2026,
    stem: "网络工程项目验收时，下列哪些测试通常属于网络连通性和性能测试范围？",
    options: ["Ping 连通性", "吞吐量测试", "时延和丢包率测试", "软件著作权登记"],
    answer: [0, 1, 2],
    explanation: "网络工程师应用技术题常结合网络规划、设备配置、测试验收和故障排查。著作权登记不属于网络性能测试。",
    points: ["网络验收", "性能测试", "故障排查"],
  },
  {
    id: "rk-test-001",
    bankId: "engineer",
    module: "软件评测师",
    type: "单选",
    difficulty: "基础",
    sourceType: "真题考点改编",
    year: 2024,
    stem: "软件评测师考试中，依据需求规格说明书设计输入条件和预期输出，通常属于？",
    options: ["黑盒测试", "白盒测试", "代码生成", "数据库备份"],
    answer: 0,
    explanation: "软件评测师重点考查测试基础、测试设计、缺陷管理、测试执行和质量评价。黑盒测试从规格出发设计用例。",
    points: ["软件评测师", "黑盒测试", "测试用例"],
  },
  {
    id: "rk-test-002",
    bankId: "engineer",
    module: "软件评测师",
    type: "多选",
    difficulty: "综合",
    sourceType: "模拟题",
    year: 2026,
    stem: "缺陷报告中通常应包含哪些关键信息？",
    options: ["复现步骤", "实际结果与期望结果", "严重程度或优先级", "开发人员家庭住址"],
    answer: [0, 1, 2],
    explanation: "高质量缺陷报告应便于复现、定位、评估影响和安排修复；无关个人隐私不应写入缺陷报告。",
    points: ["缺陷管理", "测试报告", "软件质量"],
  },
];

export const knowledgePoints = [
  {
    bankId: "ncre3",
    module: "网络技术",
    title: "网络规划与 IP 地址设计",
    summary: "按部门、业务区、安全域和未来扩展进行子网规划，明确网关、路由、地址预留和安全边界。",
    source: ncreSource,
  },
  {
    bankId: "ncre3",
    module: "网络技术",
    title: "VLAN、STP 与静态路由",
    summary: "VLAN 划分广播域，STP 防二层环路，静态路由条目关注目的网络、掩码、下一跳和出接口。",
    source: ncreSource,
  },
  {
    bankId: "ncre3",
    module: "数据库技术",
    title: "SQL、事务与数据库运维",
    summary: "重点掌握复杂查询、分组聚合、索引、存储过程、触发器、权限管理、备份恢复和性能优化。",
    source: ncreSource,
  },
  {
    bankId: "ncre3",
    module: "信息安全技术",
    title: "密码技术、风险评估与等级保护",
    summary: "区分对称/非对称加密、摘要、数字签名，并理解资产、威胁、脆弱性、控制措施和风险处置。",
    source: ncreSource,
  },
  {
    bankId: "ncre3",
    module: "信息安全技术",
    title: "SQL 注入与 XSS 防护",
    summary: "SQL 注入优先使用参数化查询；XSS 防护关注输出编码、输入校验、CSP 和 Cookie 安全属性。",
    source: ncreSource,
  },
  {
    bankId: "ncre3",
    module: "软件测试",
    title: "黑盒测试与白盒覆盖",
    summary: "黑盒测试从规格出发，白盒测试从程序结构出发；覆盖准则用于衡量语句、分支和条件执行程度。",
    source: ncreSource,
  },
  {
    bankId: "engineer",
    module: "软件设计师",
    title: "需求、设计与过程模型",
    summary: "需求分析定义做什么，设计定义怎么做；瀑布、螺旋、增量和敏捷模型适合不同风险和变化场景。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "软件设计师",
    title: "查找、树与线性结构",
    summary: "掌握栈、队列、二叉排序树、二分查找和常见排序的适用条件与复杂度。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "软件设计师",
    title: "进程调度与存储管理",
    summary: "进程状态转换、调度时机、分页地址转换、页表和缺页处理是上午题高频基础点。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "数据库系统工程师",
    title: "范式、事务与并发控制",
    summary: "围绕函数依赖、范式分解、事务 ACID、锁协议和可串行化理解数据库系统题。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "公共基础",
    title: "CPU、Cache 与存储层次",
    summary: "运算器、控制器、指令执行、Cache 命中率和局部性原理是组成原理常考点。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "系统架构设计师",
    title: "MVC、分层与微服务治理",
    summary: "理解 Model/View/Controller 职责边界，以及微服务拆分后的注册发现、契约、事务和可观测性问题。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "信息系统项目管理师",
    title: "关键路径与配置基线",
    summary: "关键路径决定最短工期；配置基线为受控变更、版本追踪和回退提供稳定参照。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "公共基础",
    title: "知识产权与质量属性",
    summary: "软件著作权保护表达形式；可靠性、可维护性、可移植性等质量属性要结合定义理解。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "程序员",
    title: "程序员：语法、算法与基础开发",
    summary: "重点覆盖 C/Java 基础语法、数组与指针、函数、简单数据结构、算法复杂度、数据库和网络基础。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "网络工程师",
    title: "网络工程师：规划、配置与排障",
    summary: "围绕 TCP/IP、交换路由、OSPF、ACL、NAT、网络安全、项目验收和常见故障定位组织练习。",
    source: engineerSource,
  },
  {
    bankId: "engineer",
    module: "软件评测师",
    title: "软件评测师：测试设计与质量评价",
    summary: "重点训练测试基础、测试用例设计、缺陷报告、自动化测试、性能测试、质量模型和评测流程。",
    source: engineerSource,
  },
];

export const knowledgeNotes = [
  {
    id: "ncre3-notes",
    bankId: "ncre3",
    title: "计算机三级学习笔记",
    summary: "按全国计算机等级考试三级的二级科目组织章节，先学基础概念，再做题巩固。",
    chapters: [
      {
        id: "ncre3-network",
        title: "网络技术",
        scope: ["网络技术"],
        summary: "网络技术科目按网络规划、交换路由、出口访问、管理排障四条线复习。",
        sections: [
          {
            id: "ncre3-network-01",
            title: "第1章 网络规划与 IP 地址",
            bullets: ["网络规划先确定业务部门、主机数量、安全域和未来扩展。", "IP 地址规划要会计算网络号、广播地址、可用主机数和前缀长度。", "子网划分题不要先背答案，要先写出地址块大小和主机容量。"],
            example: "给出 50 台主机的部门网段，判断 /26 是否足够，以及可用主机数是多少。",
            review: "为什么 /26 有 64 个地址但只有 62 个可用主机地址？",
          },
          {
            id: "ncre3-network-02",
            title: "第2章 交换网络：VLAN、Trunk 与 STP",
            bullets: ["VLAN 用于划分二层广播域，是部门隔离的常见手段。", "Trunk 链路用于承载多个 VLAN 的流量。", "STP 用于避免冗余交换链路形成二层环路。"],
            example: "财务部和研发部需要隔离广播域，优先选择 VLAN。",
            review: "同一台交换机上的不同 VLAN 为什么不能直接二层通信？",
          },
          {
            id: "ncre3-network-03",
            title: "第3章 路由、NAT 与出口访问",
            bullets: ["静态路由由目的网络、掩码、下一跳或出接口组成。", "默认路由用于把未知目的网络流量送往出口。", "NAT 常用于私有地址访问公网，也能隐藏内部地址结构。"],
            example: "企业内网 192.168.1.0/24 访问互联网，需要在出口设备上配置 NAT。",
            review: "默认路由、静态路由和直连路由的优先匹配关系是什么？",
          },
          {
            id: "ncre3-network-04",
            title: "第4章 网络管理与故障排查",
            bullets: ["排障要按物理层、链路层、网络层、应用层逐层缩小范围。", "ping、tracert、ipconfig/ifconfig 是基础排障工具。", "网络管理关注性能、配置、故障、安全和计费管理。"],
            example: "主机不能访问网关时，先检查 IP、掩码、网线、网卡和 VLAN。",
            review: "为什么排障不应该一开始就修改路由配置？",
          },
        ],
      },
      {
        id: "ncre3-database",
        title: "数据库技术",
        scope: ["数据库技术"],
        summary: "数据库技术按关系模型、SQL、事务并发、数据库运维四章推进。",
        sections: [
          {
            id: "ncre3-db-01",
            title: "第1章 关系模型与规范化",
            bullets: ["关系模型包含关系、元组、属性、域和完整性约束。", "候选码具有唯一性和最小性，主键是被选定的候选码。", "规范化题重点看函数依赖、部分依赖和传递依赖。"],
            example: "判断学生表中学号是否能作为主键，以及课程号是否应作为外键。",
            review: "候选码、主键、外键分别解决什么问题？",
          },
          {
            id: "ncre3-db-02",
            title: "第2章 SQL 查询与数据库对象",
            bullets: ["SELECT 查询按 FROM、WHERE、GROUP BY、HAVING、ORDER BY 理解。", "聚合函数包括 COUNT、SUM、AVG、MAX、MIN。", "视图、索引、触发器和存储过程是常见数据库对象。"],
            example: "按部门统计平均工资，应使用 GROUP BY 和 AVG。",
            review: "WHERE 和 HAVING 的区别是什么？",
          },
          {
            id: "ncre3-db-03",
            title: "第3章 事务、并发与恢复",
            bullets: ["ACID 是事务题的主线：原子性、一致性、隔离性、持久性。", "并发问题包括丢失修改、不可重复读和读脏数据。", "日志、检查点和备份恢复用于故障恢复。"],
            example: "事务失败后撤销已执行操作，对应原子性。",
            review: "隔离性和并发控制有什么关系？",
          },
          {
            id: "ncre3-db-04",
            title: "第4章 索引、安全与运行维护",
            bullets: ["索引能提升查询速度，但会增加写入和维护成本。", "权限管理应遵循最小权限原则。", "运行维护包含备份恢复、性能监控、空间管理和安全审计。"],
            example: "经常作为查询条件且区分度高的列更适合建索引。",
            review: "为什么不是每个字段都适合建立索引？",
          },
        ],
      },
      {
        id: "ncre3-security",
        title: "信息安全技术",
        scope: ["信息安全技术"],
        summary: "信息安全技术按密码基础、风险管理、网络安全、Web 安全分段学习。",
        sections: [
          {
            id: "ncre3-sec-01",
            title: "第1章 密码技术基础",
            bullets: ["对称加密使用同一密钥，效率高但密钥分发困难。", "非对称加密使用公钥和私钥，适合密钥交换和身份认证。", "数字签名用于身份鉴别、完整性和不可否认性。"],
            example: "数字签名不能主要用来保证机密性，它更强调不可否认性。",
            review: "加密、摘要、签名分别解决什么安全问题？",
          },
          {
            id: "ncre3-sec-02",
            title: "第2章 风险评估与等级保护",
            bullets: ["风险评估从资产、威胁、脆弱性和控制措施展开。", "等级保护关注定级、备案、建设整改、测评和监督检查。", "安全防护既有技术控制，也有管理和运维控制。"],
            example: "资产识别、威胁分析和控制措施都属于风险评估范围。",
            review: "漏洞、威胁和风险三者有什么区别？",
          },
          {
            id: "ncre3-sec-03",
            title: "第3章 Web 安全与应用防护",
            bullets: ["SQL 注入优先使用参数化查询防护。", "XSS 防护重点是输出编码和上下文隔离。", "Cookie 安全可结合 HttpOnly、Secure、SameSite 等属性。"],
            example: "拼接用户输入生成 SQL 是 SQL 注入高风险做法。",
            review: "为什么输入过滤不能完全替代参数化查询？",
          },
        ],
      },
      {
        id: "ncre3-embedded-linux",
        title: "嵌入式与 Linux",
        scope: ["嵌入式系统开发技术", "Linux应用与开发技术"],
        summary: "嵌入式强调实时性和资源约束，Linux 强调命令、权限、进程和开发环境。",
        sections: [
          {
            id: "ncre3-embedded-01",
            title: "第1章 嵌入式系统基础",
            bullets: ["嵌入式系统通常面向特定任务，资源受限。", "实时系统关注响应时间的确定性。", "中断、任务调度、互斥和通信是实时系统基础。"],
            example: "实时操作系统最关注任务能否在规定时间内响应。",
            review: "硬实时和软实时的区别是什么？",
          },
          {
            id: "ncre3-linux-01",
            title: "第2章 Linux 命令、权限与进程",
            bullets: ["ls -l 查看权限、属主、大小和时间信息。", "chmod 修改权限，chown 修改属主。", "ps、top、kill 用于查看和控制进程。"],
            example: "查看当前目录下文件详细权限信息，常用 ls -l。",
            review: "rwx 对文件和目录分别意味着什么？",
          },
        ],
      },
    ],
  },
  {
    id: "ruankao-notes",
    bankId: "engineer",
    title: "软考学习笔记",
    summary: "参考中国计算机技术职业资格网考试用书页面列出的初级、中级、高级考试大纲，按资格方向和章节组织学习。",
    chapters: [
      {
        id: "rk-common",
        title: "公共基础",
        scope: ["公共基础", "程序员", "软件设计师", "网络工程师", "数据库系统工程师", "软件评测师", "系统架构设计师", "信息系统项目管理师"],
        summary: "公共基础是软考各资格共同底座，先学计算机系统，再学操作系统、网络、数据库、法规和标准。",
        sections: [
          {
            id: "rk-common-01",
            title: "第1章 计算机系统基础",
            bullets: ["CPU 包含运算器、控制器和寄存器等部件。", "ALU 负责算术和逻辑运算。", "Cache 依靠局部性原理提高平均访存速度。"],
            example: "Cache 的主要作用是缓解 CPU 与主存速度不匹配。",
            review: "为什么 Cache 命中率会影响程序整体运行速度？",
          },
          {
            id: "rk-common-02",
            title: "第2章 操作系统基础",
            bullets: ["进程状态包括就绪、运行、阻塞等。", "分页地址由页号和页内位移组成。", "文件系统、设备管理和作业调度是操作系统常见考点。"],
            example: "进程从就绪态进入运行态，是因为被处理机调度选中。",
            review: "就绪态和阻塞态的根本区别是什么？",
          },
          {
            id: "rk-common-03",
            title: "第3章 标准化、知识产权与职业规范",
            bullets: ["软件著作权保护程序和文档等表达形式。", "算法思想本身通常不由著作权直接保护。", "质量属性包括可靠性、可维护性、可移植性等。"],
            example: "软件著作权通常保护源程序和文档等表达形式。",
            review: "可靠性、可用性、可维护性分别关注什么？",
          },
        ],
      },
      {
        id: "rk-programmer",
        title: "程序员考试大纲章节",
        scope: ["程序员"],
        summary: "程序员属于初级资格，章节重点是程序设计语言、数据结构、数据库和软件开发基础。",
        sections: [
          {
            id: "rk-programmer-01",
            title: "第1章 程序设计语言基础",
            bullets: ["掌握变量、表达式、分支、循环、函数和数组。", "C 语言数组名在多数表达式中会转换为首元素地址。", "指针题要区分地址、指针变量和指针指向的值。"],
            example: "数组名在表达式中常表示首元素地址。",
            review: "指针 p、*p、&p 分别表示什么？",
          },
          {
            id: "rk-programmer-02",
            title: "第2章 基本算法与数据结构",
            bullets: ["顺序、选择、循环是算法三种基本控制结构。", "复杂度用于描述算法随输入规模增长的资源变化。", "栈、队列、数组和链表是初级高频结构。"],
            example: "判断双重循环的时间复杂度通常从循环次数入手。",
            review: "为什么 O(n²) 算法在数据量变大时会明显变慢？",
          },
        ],
      },
      {
        id: "rk-software-designer",
        title: "软件设计师考试大纲章节",
        scope: ["软件设计师"],
        summary: "软件设计师是中级核心资格，上午覆盖基础知识，下午强调软件设计、数据库设计、算法和面向对象应用。",
        sections: [
          {
            id: "rk-sd-01",
            title: "第1章 软件工程基础",
            bullets: ["需求分析回答做什么，设计回答怎么做。", "瀑布、增量、螺旋和敏捷模型适合不同项目环境。", "测试、维护、配置管理贯穿软件生命周期。"],
            example: "明确系统必须完成什么功能，属于需求分析。",
            review: "需求规格说明书和概要设计说明书有什么区别？",
          },
          {
            id: "rk-sd-02",
            title: "第2章 数据结构与算法设计",
            bullets: ["二分查找要求顺序表有序。", "二叉排序树中序遍历得到有序序列。", "排序题要掌握时间复杂度、稳定性和适用场景。"],
            example: "若中序遍历结果有序，通常联想到二叉排序树。",
            review: "快速排序和归并排序的平均复杂度分别是什么？",
          },
          {
            id: "rk-sd-03",
            title: "第3章 数据库与信息系统设计",
            bullets: ["数据库设计从概念结构、逻辑结构到物理结构逐步细化。", "ER 图用于概念模型设计。", "范式用于减少冗余和异常，但过度规范化可能影响查询性能。"],
            example: "把实体、属性、联系画出来，属于概念结构设计。",
            review: "ER 模型如何转换成关系模式？",
          },
          {
            id: "rk-sd-04",
            title: "第4章 面向对象与设计模式",
            bullets: ["封装隐藏内部实现，继承支持复用，多态支持统一接口。", "UML 类图、用例图、顺序图是常见建模工具。", "设计模式题要理解意图，而不是死背名称。"],
            example: "类隐藏内部数据并通过方法访问，体现封装。",
            review: "继承和组合各自适合什么场景？",
          },
        ],
      },
      {
        id: "rk-network-engineer",
        title: "网络工程师考试大纲章节",
        scope: ["网络工程师"],
        summary: "网络工程师按网络基础、设备配置、安全管理、工程设计与运维验收组织。",
        sections: [
          {
            id: "rk-ne-01",
            title: "第1章 网络体系结构与协议",
            bullets: ["TCP/IP 分层用于定位协议职责。", "TCP 提供可靠传输，UDP 面向无连接。", "IP、ICMP、ARP、DNS、HTTP 等协议要按层次记忆。"],
            example: "TCP 负责确认、重传和流量控制。",
            review: "ARP 和 DNS 都是解析，它们解析的对象有什么不同？",
          },
          {
            id: "rk-ne-02",
            title: "第2章 路由交换与网络安全",
            bullets: ["OSPF 是链路状态型内部网关协议。", "ACL 用于访问控制，NAT 用于地址转换。", "网络安全要结合边界防护、身份认证、日志审计和安全策略。"],
            example: "判断 OSPF 属于链路状态型 IGP。",
            review: "ACL 放在靠近源还是靠近目的，取决于什么？",
          },
          {
            id: "rk-ne-03",
            title: "第3章 网络工程设计与验收",
            bullets: ["网络设计从需求、拓扑、地址、设备、安全和运维展开。", "验收测试包括连通性、吞吐量、时延、丢包率和可靠性。", "故障排查要保存配置变更记录。"],
            example: "Ping 连通性和吞吐量测试都属于网络验收内容。",
            review: "为什么网络验收不能只做 ping 测试？",
          },
        ],
      },
      {
        id: "rk-database-engineer",
        title: "数据库系统工程师考试大纲章节",
        scope: ["数据库系统工程师"],
        summary: "数据库系统工程师按数据库原理、设计实施、管理维护、性能安全组织。",
        sections: [
          {
            id: "rk-db-01",
            title: "第1章 数据库原理与关系理论",
            bullets: ["函数依赖是范式判断的基础。", "第二范式消除非主属性对候选码的部分依赖。", "事务 ACID 和并发控制是系统题主线。"],
            example: "两段锁协议常用于保证调度可串行化。",
            review: "部分依赖和传递依赖如何区分？",
          },
          {
            id: "rk-db-02",
            title: "第2章 数据库设计、实施与运维",
            bullets: ["数据库设计包括需求分析、概念设计、逻辑设计、物理设计。", "索引、分区、备份恢复、权限管理都是运维重点。", "性能优化要结合执行计划和业务访问模式。"],
            example: "高频查询列可以考虑索引，但要评估写入成本。",
            review: "为什么数据库设计不能直接从建表开始？",
          },
        ],
      },
      {
        id: "rk-software-test",
        title: "软件评测师考试大纲章节",
        scope: ["软件评测师"],
        summary: "软件评测师按测试基础、测试设计、执行管理、质量评价和自动化测试组织。",
        sections: [
          {
            id: "rk-test-01",
            title: "第1章 测试基础与测试设计",
            bullets: ["黑盒测试从需求规格出发。", "白盒测试从程序结构出发。", "等价类、边界值、判定表、因果图是常见黑盒方法。"],
            example: "依据需求规格说明书设计测试，属于黑盒测试。",
            review: "边界值分析为什么特别容易发现缺陷？",
          },
          {
            id: "rk-test-02",
            title: "第2章 缺陷管理与质量评价",
            bullets: ["缺陷报告应包含复现步骤、实际结果、期望结果、环境和严重程度。", "严重程度描述影响，优先级描述修复顺序。", "性能测试关注响应时间、吞吐量、资源利用率和稳定性。"],
            example: "缺陷报告中不应包含无关个人隐私。",
            review: "为什么严重程度高的缺陷不一定优先级最高？",
          },
        ],
      },
      {
        id: "rk-advanced",
        title: "高级资格考试大纲章节",
        scope: ["系统架构设计师", "信息系统项目管理师"],
        summary: "高级资格都包含综合知识、案例分析和论文，学习时要把概念、案例和表达一起训练。",
        sections: [
          {
            id: "rk-arch-01",
            title: "第1章 系统架构设计师：架构与质量属性",
            bullets: ["架构设计围绕质量属性权衡，而不是堆技术名词。", "MVC、分层、微服务、事件驱动等架构风格要理解适用场景。", "案例分析常要求说明问题、原因、方案和效果。"],
            example: "微服务拆分后需要治理服务发现、接口契约和分布式事务。",
            review: "性能、可用性和一致性冲突时如何取舍？",
          },
          {
            id: "rk-pm-01",
            title: "第2章 信息系统项目管理师：十大管理与论文",
            bullets: ["关键路径决定项目最短工期。", "配置基线是受控变更的稳定参照。", "论文要写清背景、问题、措施、效果和经验。"],
            example: "PERT 图中持续时间最长的路径是关键路径。",
            review: "风险、问题、变更三者在项目管理中分别如何处理？",
          },
        ],
      },
    ],
  },
];
